### ISSUE TITLE
Failed To Connect

### ISSUE THREAD

**Issue by jonathannaguin** [algra4/ha-edilkamin#6]
Hello,

I am trying to setup a stove but getting Failed to connect every time...

I got the Refresh Token, the ClientID and the MAC address from sniffing the HTTP Traffic of the The Mind app, where can I see the logs?

**Comment by jonathannaguin** [comment]
I just opened the system logs and can see the following:

`2024-12-07 16:54:00.442 ERROR (MainThread) [custom_components.edilkamin.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/edilkamin/config_flow.py", line 64, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/edilkamin/config_flow.py", line 44, in validate_input
    await api.check()
  File "/config/custom_components/edilkamin/api/edilkamin_async_api.py", line 133, in check
    await self.execute_put_request("check", False)
  File "/config/custom_components/edilkamin/api/edilkamin_async_api.py", line 178, in execute_put_request
    return await self.execute_request("PUT", self.url_command, json.dumps(body))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/edilkamin/api/edilkamin_async_api.py", line 192, in execute_request
    headers = await self.get_headers()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/edilkamin/api/edilkamin_async_api.py", line 233, in get_headers
    token = await self.auth.get_token()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/edilkamin/api/auth.py", line 58, in get_token
    self.access_token = data.get("AuthenticationResult").get("AccessToken")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
`

It seems the "check" method... For my own sake, I downloaded this repo into my Mac and I was able to issue commands directly from Python, still the "check" method fails there too:

```
>>> await e.check()
DEBUG:edilkamin_async_api:Check config
DEBUG:edilkamin_async_api:Endpoint URL: https://fxtj7xkgc6.execute-api.eu-central-1.amazonaws.com/prod/mqtt/command , method: PUT, body: {"name": "check", "value": false, "mac_address": "24***e4"}
DEBUG:auth:Set refresh token and client id with provided information
DEBUG:auth:Get access token
DEBUG:auth:{'AuthenticationResult': {'AccessToken': 'eyJraWQiOiI0****gHxT2uOUHUQ', 'ExpiresIn': 86400, 'IdToken': 'eyJraWQiOiJtN****Wg8s8G8QsIgigZ9rzDvzw2_O34SxQnNAH5hA', 'TokenType': 'Bearer'}, 'ChallengeParameters': {}}
DEBUG:edilkamin_async_api:Timeout connecting to Edilkamin API: 
Traceback (most recent call last):
  File "/Users/***/Downloads/ha-edilkamin-main/custom_components/edilkamin/api/edilkamin_async_api.py", line 193, in execute_request
    response = await self.session.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        method, url, headers=headers, data=body
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/***/Downloads/ha-edilkamin-main/custom_components/edilkamin/api/venv/lib/python3.13/site-packages/aiohttp/client.py", line 728, in _request
    await resp.start(conn)
  File "/Users/***/Downloads/ha-edilkamin-main/custom_components/edilkamin/api/venv/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1055, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/***/Downloads/ha-edilkamin-main/custom_components/edilkamin/api/venv/lib/python3.13/site-packages/aiohttp/streams.py", line 668, in read
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/***/Downloads/ha-edilkamin-main/custom_components/edilkamin/api/edilkamin_async_api.py", line 185, in execute_request
    async with async_timeout.timeout(30):
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/timeouts.py", line 116, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "<python-input-100>", line 1, in <module>
    await e.check()
  File "/Users/***/Downloads/ha-edilkamin-main/custom_components/edilkamin/api/edilkamin_async_api.py", line 133, in check
    await self.execute_put_request("check", False)
  File "/Users/***/Downloads/ha-edilkamin-main/custom_components/edilkamin/api/edilkamin_async_api.py", line 178, in execute_put_request
    return await self.execute_request("PUT", self.url_command, json.dumps(body))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/***/Downloads/ha-edilkamin-main/custom_components/edilkamin/api/edilkamin_async_api.py", line 228, in execute_request
    raise HttpException(message, "Time out", 408)
edilkamin_async_api.HttpException: Timeout connecting to Edilkamin API, body = {body}.
```

**Comment by algra4** [comment]
Hello @jonathannaguin, 

That's strange I'll try to look at your problem when I have time. 

P.S: I'm thinking of using pycognito for authentication to avoid sniffing packets.
